# cargo-deny configuration

[advisories]
# The advisories section is used to detect crates with security vulnerabilities
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "Unicode-3.0",
    "Unlicense",
]

# The confidence threshold for detecting a license from license text
confidence-threshold = 0.8

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"

# List of explicitly disallowed crates
deny = []

# Skip certain crates when checking for duplicates
skip = []

# Similarly named crates that are allowed to coexist
skip-tree = []

[sources]
# Lint level for what to happen when a crate from a crate registry that is not in the allow list is encountered
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []